[versions]
agp = "8.8.2"
kotlin = "2.1.0"
compose = "1.7.8"
compose-material3 = "1.3.1"
androidx-activityCompose = "1.10.1"
googleServices = "4.4.2"
firebaseBom = "33.10.0"
playServicesAds = "24.0.0"
serialization = "2.0.20"
gitliveFirebase = "2.1.0"
gitliveFirebaseRealtimeDatabase = "2.1.0"
jsonSerialization = "1.7.3"
coroutinesCore = "1.9.0-RC.2"
koinBom = "4.0.2"
ksp = "2.1.0-1.0.29"
koinAnnotationBom = "2.0.0-RC1"
dataStore = "1.1.3"
protobuf = "4.29.3"
protobufGoogle = "0.9.3"
compose-navigation = "2.8.8"

[libraries]
kotlin-test = { module = "org.jetbrains.kotlin:kotlin-test", version.ref = "kotlin" }
androidx-activity-compose = { module = "androidx.activity:activity-compose", version.ref = "androidx-activityCompose" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" }
compose-ui-tooling-preview = { module = "androidx.compose.ui:ui-tooling-preview", version.ref = "compose" }
compose-foundation = { module = "androidx.compose.foundation:foundation", version.ref = "compose" }
compose-material3 = { module = "androidx.compose.material3:material3", version.ref = "compose-material3" }
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-databse = { module = "com.google.firebase:firebase-database" }
play-services-ads = { module = "com.google.android.gms:play-services-ads", version.ref = "playServicesAds" }
gitlive-firebase-common = { module = "dev.gitlive:firebase-common", version.ref = "gitliveFirebase" }
gitlive-firebase-database = { module = "dev.gitlive:firebase-database", version.ref = "gitliveFirebaseRealtimeDatabase" }
json-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "jsonSerialization" }
coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "coroutinesCore" }
koin-bom = { module = "io.insert-koin:koin-bom", version.ref = "koinBom" }
koin-core = { module = "io.insert-koin:koin-core", version.ref = "koinBom" }
koin-test = { module = "io.insert-koin:koin-test" }
koin-android = { module = "io.insert-koin:koin-android" }
koin-compose = { module = "io.insert-koin:koin-androidx-compose" }
koin-compose-navigation = { module = "io.insert-koin:koin-androidx-compose-navigation" }
koin-annotations-bom = { module = "io.insert-koin:koin-annotations-bom", version.ref = "koinAnnotationBom" }
koin-annotations = { module = "io.insert-koin:koin-annotations", version.ref = "koinAnnotationBom" }
koin-compiler = { module = "io.insert-koin:koin-ksp-compiler", version.ref = "koinAnnotationBom" }
dataStore = { module = "androidx.datastore:datastore", version.ref = "dataStore" }
protobuf-java = { module = "com.google.protobuf:protobuf-javalite", version.ref = "protobuf" }
protobuf-kotlin = { module = "com.google.protobuf:protobuf-kotlin-lite", version.ref = "protobuf" }
compose-navigation = { module = "androidx.navigation:navigation-compose", version.ref = "compose-navigation" }
compose-navigation-testing = { module = "androidx.navigation:navigation-testing", version.ref = "compose-navigation" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlinMultiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlinCocoapods = { id = "org.jetbrains.kotlin.native.cocoapods", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
google-services = { id = "com.google.gms.google-services", version.ref = "googleServices" }
seraliziation = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "serialization" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }
protobuf = { id = "com.google.protobuf", version.ref = "protobufGoogle" }
